### Tensor 이해

[1] 모듈 로딩

In [3]:
import torch

- Tensor 생성  
[2] torch.rand()

In [11]:
# 0 <= ~ <1 범위의 임의의 숫자 1개 추출 => rand
torch.manual_seed(1)

# * 가변인자 
# ** 키워드파라미터
# rand(*size) : 가변인자 => 몇 차원일지 알수 없음!
dataTS1=torch.rand(4)
dataTS2=torch.rand(2,4)
dataTS3=torch.rand(3,2,4)

In [12]:
print(dataTS1)
print(dataTS2)
print(dataTS3)

tensor([0.7576, 0.2793, 0.4031, 0.7347])
tensor([[0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
tensor([[[0.6826, 0.3051, 0.4635, 0.4550],
         [0.5725, 0.4980, 0.9371, 0.6556]],

        [[0.3138, 0.1980, 0.4162, 0.2843],
         [0.3398, 0.5239, 0.7981, 0.7718]],

        [[0.0112, 0.8100, 0.6397, 0.9743],
         [0.8300, 0.0444, 0.0246, 0.2588]]])


- Tensor생성  
[3] torch.randn()

In [13]:
dataTS1=torch.randn(4)
dataTS2=torch.randn(2,4)
dataTS3=torch.randn(3,2,4)

print(dataTS1)
print(dataTS2)
print(dataTS3)

tensor([-1.5727, -0.1232,  3.5870, -1.8313])
tensor([[ 1.5987, -1.2770,  0.3255, -0.4791],
        [ 1.3790,  2.5286,  0.4107, -0.9880]])
tensor([[[ 0.4533,  1.1422,  0.2486, -1.7754],
         [-0.0255, -1.0233, -0.5962, -1.0055]],

        [[-1.4344, -0.5008,  0.1716, -0.1600],
         [-0.5047, -1.4746, -0.3416, -0.3003]],

        [[-1.0483, -0.4709,  0.2911,  1.9907],
         [-0.9247, -0.9301,  1.4301,  0.4208]]])


- Tensor 생성  
[3] torch.randint()

In [23]:
dataTS1=torch.randint(1,46,(6,))        # 1D Vector
dataTS2=torch.randint(1,46,(6,5))       # 2D Matrix
dataTS3=torch.randint(1,5,(6,2,3))      # 3D Tensor

print(dataTS1)
print(dataTS2)
print(dataTS3)

tensor([11, 14, 20, 26, 41, 25])
tensor([[17,  9, 18, 25,  1],
        [32, 21, 31, 31, 21],
        [39, 39, 30, 14, 39],
        [16, 10, 44,  7, 33],
        [ 6, 38, 34, 32, 43],
        [34, 34, 18,  5, 29]])
tensor([[[4, 2, 4],
         [3, 3, 2]],

        [[2, 4, 4],
         [3, 3, 4]],

        [[2, 3, 4],
         [4, 4, 4]],

        [[3, 2, 2],
         [4, 1, 1]],

        [[2, 1, 3],
         [1, 3, 1]],

        [[2, 2, 4],
         [1, 4, 4]]])
