## Tensor의 모양/형태/shape 변경과 View Tensor

In [106]:
### 모듈 로딩
import torch
import numpy as np

In [107]:
## 텐서 생성
dataTS = torch.arange(1,21)
print(dataTS, dataTS.ndim , dataTS.stride(),sep='\n')

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
1
(1,)


In [108]:
# 1D => 2D 형태/모양/shape 변경
dataTS2=dataTS.reshape((-1,5))
print(dataTS2, dataTS2.ndim , dataTS2.stride(),sep='\n')
print(f' is_contiguous() : {dataTS22.is_contiguous()}')

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
2
(5, 1)
 is_contiguous() : True


In [109]:
print(dataTS2.storage())

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]


In [110]:
dataTS22=dataTS2.reshape((-1,2))
print(dataTS22, dataTS22.ndim , dataTS22.stride(),sep='\n')
print(f' is_contiguous() : {dataTS22.is_contiguous()}')

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]])
2
(2, 1)
 is_contiguous() : True


In [111]:
dataTS23=dataTS22.T
dataTS23.is_contiguous()

False

In [112]:
dataTS23.storage()

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]

In [113]:
## 불연속적 ==> 연속적으로 저장되도록 
# 새 메모리를 사용 copy() 의 역할할
dataTS24=dataTS23.contiguous()
dataTS24

tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]])

In [114]:
dataTS24.storage()

 1
 3
 5
 7
 9
 11
 13
 15
 17
 19
 2
 4
 6
 8
 10
 12
 14
 16
 18
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]

In [116]:
#print(id(dataTS22[1]),id(dataTS24[1]))

2431661984400 2431661984400


In [128]:
aa=torch.tensor([[[1,2,3],[4,5,6]]])
aa.shape

torch.Size([1, 2, 3])

In [138]:
torch.permute(aa,(2,1,0)).shape

torch.Size([3, 2, 1])