### Tensor 변환
- torch.as_tensor()
    - 동일 타입과 동일 디바이스를 가진 데이터 존재 => view 즉, 데이터 공유
    - 다른 타입 또는 다른 디바이스를 사진 데이터 라면 => copy 즉, 생성
    -  view tensor() 또는 copy tensor()

In [210]:
### 모듈로딩
import torch

- Python 객체 ==> Tensor 변환

In [211]:
### List ==> Tensor 
data=list(range(1,10))

In [212]:
# torch.as_tensor()
dataTS=torch.as_tensor(data,dtype=torch.int8)
dataTS,dataTS.shape , dataTS.ndim

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8), torch.Size([9]), 1)

1. DATA 공유
- 형태/ 모양 shape만 변경
- view방식
2. 새롭게 생성
-  Data 새롭게 메모리
- copy 방식

In [213]:
data[0]=100
data,dataTS

([100, 2, 3, 4, 5, 6, 7, 8, 9],
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8))

## Numpy ndarray 객체 => Tensor 변환

In [214]:
import numpy as np

### copy방식 or view 방식
- as_tensor()
    - 같은 디바이스이면 view
    - 다른 디바이스면 copy

In [216]:
arr1=np.array([1,2,3])
arr1,arr1.dtype,arr1.ndim

(array([1, 2, 3]), dtype('int32'), 1)

In [217]:
arrTS=torch.as_tensor(arr1)
arrTS
# view 방식

tensor([1, 2, 3], dtype=torch.int32)

In [218]:
arr1[0]=77
arr1,arrTS

(array([77,  2,  3]), tensor([77,  2,  3], dtype=torch.int32))

In [219]:
arrTS[0]=99
arr1,arrTS

(array([99,  2,  3]), tensor([99,  2,  3], dtype=torch.int32))

### view 방식
- Numpy ndarray ==> Tensor 변환 : from_numpy()

In [220]:
arr2=np.array([5,7,9],dtype=np.float32)
print(f' {arr2}')
print(f' 데이터 저장 메모리{arr2.data}')
print(f' 원소/요소 개수 {arr2.size}')
print(f' 원소/요소 1개 크기 {arr2.itemsize}')
print(f' 타입 {arr2.dtype}')
print(f' 방향 {arr2.strides}')

 [5. 7. 9.]
 데이터 저장 메모리<memory at 0x000001C0620A71C0>
 원소/요소 개수 3
 원소/요소 1개 크기 4
 타입 float32
 방향 (4,)


In [221]:
arr3=np.array([[5,7,9],[1,2,3]],dtype=np.float32)
print(f' {arr3}')
print(f' 데이터 저장 메모리{arr3.data}')
print(f' 원소/요소 개수 {arr3.size}')
print(f' 원소/요소 1개 크기 {arr3.itemsize}')
print(f' 타입 {arr3.dtype}')
print(f' 방향 {arr3.strides}')     # (다음줄 까지 몇 바이트 , 옆 원소까지 몇바이트)

 [[5. 7. 9.]
 [1. 2. 3.]]
 데이터 저장 메모리<memory at 0x000001C061BCCE10>
 원소/요소 개수 6
 원소/요소 1개 크기 4
 타입 float32
 방향 (12, 4)


In [222]:
arr4=np.array([[5],[7],[9]],dtype=np.float32)
print(f' {arr4}')
print(f' 데이터 저장 메모리{arr4.data}')
print(f' 원소/요소 개수 {arr4.size}')
print(f' 원소/요소 1개 크기 {arr4.itemsize}')
print(f' 타입 {arr4.dtype}')
print(f' 방향 {arr4.strides}')

 [[5.]
 [7.]
 [9.]]
 데이터 저장 메모리<memory at 0x000001C061BCCE10>
 원소/요소 개수 3
 원소/요소 1개 크기 4
 타입 float32
 방향 (4, 4)


In [223]:
arrTS=torch.from_numpy(arr2)
arrTS

tensor([5., 7., 9.])

In [224]:
arr2[0]=10
arr2,arrTS

(array([10.,  7.,  9.], dtype=float32), tensor([10.,  7.,  9.]))

## copy 방식

In [228]:
arrTS=torch.tensor(arr1)
arr1,arrTS

(array([20,  2,  3]), tensor([20,  2,  3], dtype=torch.int32))

In [226]:
arr1[0]=20
arr1,arrTS

(array([20,  2,  3]), tensor([99,  2,  3], dtype=torch.int32))

In [227]:
arrTS[0]=30
arr1,arrTS

(array([20,  2,  3]), tensor([30,  2,  3], dtype=torch.int32))