In [36]:
import numpy as np

# 방정식, 미적분, 합성곱 알아보기
## 방정식 알아보기
### 방정식 처리 알아보기
- poly1d
    - $ x^2 -2x +1$

In [37]:
ef=np.array([1,-2,1])
p=np.poly1d(ef)
p

poly1d([ 1, -2,  1])

In [38]:
print(p)

   2
1 x - 2 x + 1


In [39]:
type(p)

numpy.poly1d

In [40]:
p.variable

'x'

- coef, coefficients, coeffs : 계수구하기

In [41]:
p.coef

array([ 1, -2,  1])

In [42]:
p.coefficients

array([ 1, -2,  1])

In [43]:
p.coeffs

array([ 1, -2,  1])

- roots : 해구하기

In [44]:
p.roots

array([1.+6.68896751e-09j, 1.-6.68896751e-09j])

In [45]:
p(0)

1

- ployval :  x에 숫자대입


In [46]:
np.polyval([1,-2,1],0)

1

In [47]:
np.polyval([1,-2,1],5)

16

### 연립방정식 이해하기

- 함수사용

In [48]:
a=np.array([[1,0,0],[1,1,1],[6,7,0]])
b=np.array([0,24,0])

In [49]:
x=np.linalg.solve(a,b)
x

array([ 0., -0., 24.])

- 역행렬 사용

In [50]:
a_1 = np.linalg.inv(a)
x=np.dot(a_1,b)
x

array([ 0.,  0., 24.])

- lstsq 함수 사용

In [51]:
np.linalg.matrix_rank(A)

3

In [52]:
x, resid, rank, singulr=np.linalg.lstsq(A,b,rcond=-1)
x

array([ 3.05504346e-15, -2.56636673e-15,  2.40000000e+01])

In [ ]:
np.allclose(np.dot(A,x),b)