In [2]:
import numpy as np

## 배열의 패딩처리
### 패딩 : 기존 배열 밖에 다른 원소를 더 붙여서 배열을 확장

In [3]:
x=np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [4]:
z=np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
z[:2,:2]=x
z

array([[1., 2., 0.],
       [3., 4., 0.],
       [0., 0., 0.]])

- pad( "constant") :상수값으로 패딩

In [6]:
np.pad(x,0,"constant")

array([[1, 2],
       [3, 4]])

In [7]:
np.pad(x,(0,1),"constant")

array([[1, 2, 0],
       [3, 4, 0],
       [0, 0, 0]])

In [8]:
np.pad(x,(1,0),"constant")

array([[0, 0, 0],
       [0, 1, 2],
       [0, 3, 4]])

In [9]:
np.pad(x,(1,1),"constant")

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [10]:
np.pad(x,(3,3),"constant")

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 0, 0, 0],
       [0, 0, 0, 3, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

- pad( "edge") : 기존배열의 값으로 패딩

In [11]:
x=np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [12]:
np.pad(x,(0,1),'edge')

array([[1, 2, 2],
       [3, 4, 4],
       [3, 4, 4]])

In [13]:
np.pad(x,(1,0),'edge')

array([[1, 1, 2],
       [1, 1, 2],
       [3, 3, 4]])

In [14]:
np.pad(x,(1,1),'edge')

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

In [15]:
np.pad(x,(3,3),'edge')

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4]])

- pad() : 패딩 되는 값 maximum minimum mean median

In [16]:
np.pad(x,(3,3),"maximum")

array([[4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4]])

In [17]:
np.pad(x,(3,3),"minimum")

array([[1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [3, 3, 3, 3, 4, 3, 3, 3],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1]])

In [18]:
np.pad(x,(3,3),"mean")

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])

In [19]:
np.pad(x,(3,3),"median")

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])