In [51]:
import numpy as np

# 방정식, 미적분, 합성곱 알아보기
## 방정식 알아보기
### 방정식 처리 알아보기
- poly1d
    - $ x^2 -2x +1$

In [52]:
ef=np.array([1,-2,1])
p=np.poly1d(ef)
p

poly1d([ 1, -2,  1])

In [53]:
print(p)

   2
1 x - 2 x + 1


In [54]:
type(p)

numpy.poly1d

In [55]:
p.variable

'x'

- coef, coefficients, coeffs : 계수구하기

In [56]:
p.coef

array([ 1, -2,  1])

In [57]:
p.coefficients

array([ 1, -2,  1])

In [58]:
p.coeffs

array([ 1, -2,  1])

- roots : 해구하기

In [59]:
p.roots

array([1.+6.68896751e-09j, 1.-6.68896751e-09j])

In [60]:
p(0)

1

- ployval :  x에 숫자대입


In [61]:
np.polyval([1,-2,1],0)

1

In [62]:
np.polyval([1,-2,1],5)

16

### 연립방정식 이해하기

- 함수사용

In [63]:
a=np.array([[1,0,0],[1,1,1],[6,7,0]])
b=np.array([0,24,0])

In [64]:
x=np.linalg.solve(a,b)
x

array([ 0., -0., 24.])

- 역행렬 사용

In [65]:
a_1 = np.linalg.inv(a)
x=np.dot(a_1,b)
x

array([ 0.,  0., 24.])

- lstsq 함수 사용

In [66]:
np.linalg.matrix_rank(a)

3

In [67]:
x, resid, rank, singulr=np.linalg.lstsq(a,b,rcond=-1)
x

array([ 3.05504346e-15, -2.56636673e-15,  2.40000000e+01])

In [68]:
np.allclose(np.dot(a,x),b)

True

## 차분, 미분과 적분
- diff : 차분 함수
    - 하나의 배열 내의 원소들 간의 차를 구한 결과

In [69]:
x=np.array([1,2,4,7,10])
x

array([ 1,  2,  4,  7, 10])

In [70]:
np.diff(x)

array([1, 2, 3, 3])

In [71]:
np.diff(x,n=2)

array([1, 1, 0])

In [72]:
c=np.diff(x)
np.diff(c)

array([1, 1, 0])

### diff 함수로 미분하기

In [73]:
x=np.array([1,2,3,4,5,6])
dx=np.diff(x)
dx

array([1, 1, 1, 1, 1])

In [74]:
y=np.array([2,4,6,8,10,12])
dy=np.diff(y)
dy

array([2, 2, 2, 2, 2])

In [75]:
dydx=np.zeros(y.shape,np.float64)
dydx[:-1]=dy/dx
dydx

array([2., 2., 2., 2., 2., 0.])

In [76]:
dydx[-1]=(y[-1]-y[-2])/(x[-1]-x[-2])
dydx

array([2., 2., 2., 2., 2., 2.])

In [77]:
np.gradient(y)

array([2., 2., 2., 2., 2., 2.])

### 다항식으로 미분하기
- polyder  
$ y= x^2 -2x +1$  
$ dy \over dx $ $= 2x-2$

In [78]:
a=np.array([1,-2,1])
p=np.poly1d(a)
print(p)

   2
1 x - 2 x + 1


In [79]:
d=np.polyder(p)
d

poly1d([ 2, -2])

In [80]:
d(10)

18

### 중앙 차분으로 미분 구하기

In [81]:
def f(x):
    return x**2

In [82]:
def numerical_differentiation(f,x): ## 수치미분
    delta_x=1e-7 # 0.0000001
    return (f(x+delta_x)-f(x-delta_x))/delta_x*2

In [83]:
x= 10
nd=numerical_differentiation(f,x)
nd

79.99999951380232

### 다차원 미분
- gradient

In [84]:
x=np.linspace(0,10)
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [85]:
y=(x**2)+1
y

array([  1.        ,   1.04164931,   1.16659725,   1.37484382,
         1.666389  ,   2.04123282,   2.49937526,   3.04081633,
         3.66555602,   4.37359434,   5.16493128,   6.03956685,
         6.99750104,   8.03873386,   9.16326531,  10.37109538,
        11.66222407,  13.0366514 ,  14.49437734,  16.03540192,
        17.65972511,  19.36734694,  21.15826739,  23.03248646,
        24.99000416,  27.03082049,  29.15493544,  31.36234902,
        33.65306122,  36.02707205,  38.48438151,  41.02498959,
        43.64889629,  46.35610162,  49.14660558,  52.02040816,
        54.97750937,  58.0179092 ,  61.14160766,  64.34860475,
        67.63890046,  71.01249479,  74.46938776,  78.00957934,
        81.63306955,  85.33985839,  89.12994586,  93.00333195,
        96.96001666, 101.        ])

In [86]:
dydx=np.gradient(y)
dydx

array([0.04164931, 0.08329863, 0.16659725, 0.24989588, 0.3331945 ,
       0.41649313, 0.49979175, 0.58309038, 0.666389  , 0.74968763,
       0.83298626, 0.91628488, 0.99958351, 1.08288213, 1.16618076,
       1.24947938, 1.33277801, 1.41607663, 1.49937526, 1.58267389,
       1.66597251, 1.74927114, 1.83256976, 1.91586839, 1.99916701,
       2.08246564, 2.16576426, 2.24906289, 2.33236152, 2.41566014,
       2.49895877, 2.58225739, 2.66555602, 2.74885464, 2.83215327,
       2.9154519 , 2.99875052, 3.08204915, 3.16534777, 3.2486464 ,
       3.33194502, 3.41524365, 3.49854227, 3.5818409 , 3.66513953,
       3.74843815, 3.83173678, 3.9150354 , 3.99833403, 4.03998334])

In [87]:
np.gradient(y,2)

array([0.02082466, 0.04164931, 0.08329863, 0.12494794, 0.16659725,
       0.20824656, 0.24989588, 0.29154519, 0.3331945 , 0.37484382,
       0.41649313, 0.45814244, 0.49979175, 0.54144107, 0.58309038,
       0.62473969, 0.666389  , 0.70803832, 0.74968763, 0.79133694,
       0.83298626, 0.87463557, 0.91628488, 0.95793419, 0.99958351,
       1.04123282, 1.08288213, 1.12453145, 1.16618076, 1.20783007,
       1.24947938, 1.2911287 , 1.33277801, 1.37442732, 1.41607663,
       1.45772595, 1.49937526, 1.54102457, 1.58267389, 1.6243232 ,
       1.66597251, 1.70762182, 1.74927114, 1.79092045, 1.83256976,
       1.87421908, 1.91586839, 1.9575177 , 1.99916701, 2.01999167])

### 적분 알아보기
$\int_{0}^{4} x^2 dx$

- trapz

In [88]:
x2=np.arange(5)
x2

array([0, 1, 2, 3, 4])

In [89]:
y2=x2**2
np.trapz(y2,x=x2)

22.0

In [90]:
from scipy.integrate import quad
x2=lambda x:x**2
quad(x2,0,4)

(21.333333333333336, 2.368475785867001e-13)

## 합성곱 및 필터링 알아보기
### 1D 합성곱 함수 알아보기
<image src=https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Comparison_convolution_correlation.svg/600px-Comparison_convolution_correlation.svg.png>

- convolve (입력데이터, 필터, mode =연산횟수)

In [122]:
a=np.array([0,1,2,3,4,5,6])
v=np.array([0.2,0.7])

In [123]:
same=np.convolve(a,v,mode='same')
same.shape

(7,)

In [124]:
same

array([0. , 0.2, 1.1, 2. , 2.9, 3.8, 4.7])

In [125]:
full=np.convolve(a,v,mode='full')
full.shape

(8,)

In [126]:
full

array([0. , 0.2, 1.1, 2. , 2.9, 3.8, 4.7, 4.2])

### 2D 합성곱 함수 알아보기
- scipy.sigmal 모듈 import
- convolve2d

In [96]:
A=[[5,4,5,4],[3,2,3,2],[5,4,5,4],[3,2,3,2]]
A=np.array(A)
k=np.array([[0.717,0.707]])

In [97]:
from scipy import signal

In [98]:
grad=signal.convolve2d(A,k,boundary='fill',mode='full')
grad.shape

(4, 5)

In [99]:
grad.shape

(4, 5)

In [100]:
grad

array([[3.585, 6.403, 6.413, 6.403, 2.828],
       [2.151, 3.555, 3.565, 3.555, 1.414],
       [3.585, 6.403, 6.413, 6.403, 2.828],
       [2.151, 3.555, 3.565, 3.555, 1.414]])

### 필터링 알아보기
- filterinf : 같은 형상 배열을 만듦

In [101]:
B=[[3,4,5,2,3],[3,5,1,2,7],[2,2,5,6,7]]
B=np.array(B)
B

array([[3, 4, 5, 2, 3],
       [3, 5, 1, 2, 7],
       [2, 2, 5, 6, 7]])

In [102]:
from scipy.ndimage import maximum_filter,minimum_filter

In [103]:
maximum_filter(B,size=(2,2))

array([[3, 4, 5, 5, 3],
       [3, 5, 5, 5, 7],
       [3, 5, 5, 6, 7]])

In [104]:
maximum_filter(B,footprint=np.ones((3,3)))

array([[5, 5, 5, 7, 7],
       [5, 5, 6, 7, 7],
       [5, 5, 6, 7, 7]])

In [105]:
minimum_filter(B,size=(2,2))

array([[3, 3, 4, 2, 2],
       [3, 3, 1, 1, 2],
       [2, 2, 1, 1, 2]])

In [106]:
minimum_filter(B,footprint=np.ones((3,3)))

array([[3, 1, 1, 1, 2],
       [2, 1, 1, 1, 2],
       [2, 1, 1, 1, 2]])

### 풀링 알아보기
- pooling : 더 작은 배열을 만드는 방법

In [107]:
import skimage.measure

In [111]:
B

array([[3, 4, 5, 2, 3],
       [3, 5, 1, 2, 7],
       [2, 2, 5, 6, 7]])

In [108]:
sk=skimage.measure.block_reduce(B,(1,1),np.max)
sk

array([[3, 4, 5, 2, 3],
       [3, 5, 1, 2, 7],
       [2, 2, 5, 6, 7]])

In [109]:
sk=skimage.measure.block_reduce(B,(1,2),np.max)
sk

array([[4, 5, 3],
       [5, 2, 7],
       [2, 6, 7]])

In [110]:
sk=skimage.measure.block_reduce(B,(2,1),np.max)
sk

array([[3, 5, 5, 2, 7],
       [2, 2, 5, 6, 7]])