In [271]:
import numpy as np

# 수학 함수 알아보기
## 산술함수

- fix, trunc : 소수점이하 버리기


In [272]:
a=np.array([3.14,4.32, 5.56])
a

array([3.14, 4.32, 5.56])

In [273]:
np.fix(a)

array([3., 4., 5.])

In [274]:
np.trunc(a)

array([3., 4., 5.])

- ceil : 소수점 이하 올림
- floor : 소수점이하 버림

In [275]:
b=np.array([3.14,4.32,5.56])
np.ceil(b)

array([4., 5., 6.])

In [276]:
np.floor(b)

array([3., 4., 5.])

- round,around : 반올림 
    - 소수점 이하, 이상 들다 가능!

In [277]:
np.round(b)

array([3., 4., 6.])

In [278]:
np.around(b)

array([3., 4., 6.])

In [279]:
c=np.array([5.55,6.66])

In [280]:
np.round(c,-1)

array([10., 10.])

In [281]:
np.around(c,-1)

array([10., 10.])

산술 연산

In [282]:
x=np.array([2,4,5,8,9])
x+x

array([ 4,  8, 10, 16, 18])

In [283]:
np.add(x,x)

array([ 4,  8, 10, 16, 18])

In [284]:
x/x

array([1., 1., 1., 1., 1.])

In [285]:
x//x

array([1, 1, 1, 1, 1])

- 나머지와 몫을 구하는 함수

In [286]:
np.mod(4,3)

1

In [287]:
np.remainder(4,3)

1

In [288]:
np.divmod(4,3)

(1, 1)

- sign, negative, positive : 부호
- abs, absolute : 절대값

In [289]:
x=np.array([2,4,-5,8,-9])
x

array([ 2,  4, -5,  8, -9])

In [290]:
np.sign(x)

array([ 1,  1, -1,  1, -1])

In [291]:
np.negative(x)

array([-2, -4,  5, -8,  9])

In [292]:
np.positive(x)

array([ 2,  4, -5,  8, -9])

In [293]:
np.abs(x)

array([2, 4, 5, 8, 9])

In [294]:
np.absolute(x)

array([2, 4, 5, 8, 9])

- square , power : 제곱
- sqrt : 제곱근

In [295]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [296]:
np.square(a)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [297]:
np.power(a,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [298]:
np.power(a,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [299]:
np.sqrt(np.power(a,2))

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## 논리 및 비교 연산
- 논리연산
- logical_and , logical_or, logical_xor, ~z ,logical_not

In [300]:
True & False

False

In [301]:
True  and False

False

In [302]:
np.logical_and(True,False)

False

비교 연산
- less, greater, equal, less_equal, greater_equal, not equal

In [303]:
y=x<5
y

array([ True,  True,  True, False,  True])

In [304]:
np.less(x,5)

array([ True,  True,  True, False,  True])

In [305]:
z=x>5
z

array([False, False, False,  True, False])

In [306]:
np.greater(x,5)

array([False, False, False,  True, False])

- 수열의 합  
- sum : 총합
- cumsum : 누적 합  
$ 	\sum_{k=1}^N a_k $

In [307]:
a= np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [308]:
np.sum(a)

55

In [309]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

- 수열의 곱
- prod : 곱
- cunprod : 누적 곱  
$ 	\prod_{i=1}^N x_i$


In [310]:
b=np.arange(1,11).reshape(2,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [311]:
np.prod(b)

3628800

In [312]:
np.prod(b,axis=0)

array([ 6, 14, 24, 36, 50])

In [313]:
np.prod(b,axis=1)

array([  120, 30240])

In [314]:
np.cumprod(b)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [315]:
np.cumprod(b,axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6, 14, 24, 36, 50]])

In [316]:
np.cumprod(b,axis=1)

array([[    1,     2,     6,    24,   120],
       [    6,    42,   336,  3024, 30240]])

- 결측값 계산
- nansum, nancumsum, nanprod, nancumprod

In [317]:
c=np.arange(1,11).reshape(2,5).astype('float')
c[0,2]=np.nan
c[1,2]=np.nan
c

array([[ 1.,  2., nan,  4.,  5.],
       [ 6.,  7., nan,  9., 10.]])

In [318]:
np.sum(c)

nan

In [319]:
np.nansum(c)

44.0

In [320]:
np.nancumsum(c)

array([ 1.,  3.,  3.,  7., 12., 18., 25., 25., 34., 44.])

In [321]:
np.prod(c)

nan

In [322]:
np.nanprod(c)

151200.0

In [323]:
np.nancumprod(c)

array([1.000e+00, 2.000e+00, 2.000e+00, 8.000e+00, 4.000e+01, 2.400e+02,
       1.680e+03, 1.680e+03, 1.512e+04, 1.512e+05])

## 지수과 로그함수 이해하기
- exp : 자연 상수 e

In [324]:
np.exp(0)

1.0

In [325]:
np.exp(-2)

0.1353352832366127

In [326]:
a=np.power(np.e,2)
a

7.3890560989306495

In [327]:
b=np.power(np.e,3)
b

20.085536923187664

In [328]:
np.exp(2+3)

148.4131591025766

### 지수함수

In [329]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [330]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [331]:
np.power(np.e,x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

- exp2(x) =$ 2^x$

In [332]:
np.exp2(x)

array([ 1.,  2.,  4.,  8., 16.])

In [333]:
np.power(2,x)

array([ 1,  2,  4,  8, 16], dtype=int32)

### 로그함수
- log(x)

In [334]:
x=np.arange(10000,1000000,100000)
x

array([ 10000, 110000, 210000, 310000, 410000, 510000, 610000, 710000,
       810000, 910000])

In [335]:
np.log(x)

array([ 9.21034037, 11.60823564, 12.25486281, 12.64432758, 12.92391244,
       13.142166  , 13.32121424, 13.47302025, 13.60478953, 13.72119988])

In [336]:
np.ceil(np.log(x))

array([10., 12., 13., 13., 13., 14., 14., 14., 14., 14.])

In [337]:
np.exp(9.21034037)

9999.99998023818

In [338]:
np.allclose(np.exp(9.21034037),10000)

True

## 집합 이해하기

In [339]:
x=np.array([[1,2,3],[4,5,6],[3,4,5]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5]])

- unique : 중복제거 (집합)

In [340]:
np.unique(x)

array([1, 2, 3, 4, 5, 6])

In [341]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

- in1d : 원소의 유일성 판단

In [342]:
np.in1d(5,x)

array([False])

In [343]:
np.in1d(4,x)

array([ True])

In [344]:
np.in1d([3,4,5],x)

array([ True,  True, False])

### 집합연산
- union1d : 합집합
- intersect1d : 교집합

In [345]:
x=np.array([[1,2,3],[4,5,6],[3,4,5]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5]])

In [346]:
y=np.array([[11,21,13],[4,15,6],[3,14,5]])
y

array([[11, 21, 13],
       [ 4, 15,  6],
       [ 3, 14,  5]])

In [347]:
np.union1d(x,y)

array([ 1,  2,  3,  4,  5,  6, 11, 13, 14, 15, 21])

In [348]:
np.intersect1d(x,y)

array([3, 4, 5, 6])

- setdiff1d : 차집합
- setxor1d :  대칭차집합

In [349]:
a=np.unique(x)
a

array([1, 2, 3, 4, 5, 6])

In [350]:
b=np.unique(y)
b

array([ 3,  4,  5,  6, 11, 13, 14, 15, 21])

In [351]:
c= np.setdiff1d(a,b)
c

array([1, 2])

In [352]:
d=np.setxor1d(a,b)
d

array([ 1,  2, 11, 13, 14, 15, 21])

## 삼각함수 이해하기
- sin cos tan

In [365]:
a=np.array([0,30,45,60,90])

In [366]:
np.sin(a * np.pi /180.)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [367]:
np.sin(np.radians(a))

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [369]:
np.cos(np.radians(a))

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [370]:
np.tan(np.radians(a))

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])