In [4]:
import numpy as np

# 넘파이 특화 함수 알아보기
## 일반함수와 람다함수 사용하기
### 유니버셜 함수
- ufunc

In [5]:
np.ufunc

numpy.ufunc

In [6]:
type(np.add)

numpy.ufunc

In [7]:
for i in dir(np.ufunc):
    if not i.startswith('_'):
        print(i)

accumulate
at
identity
nargs
nin
nout
ntypes
outer
reduce
reduceat
resolve_dtypes
signature
types


### 유니버셜함수 : 내부 메소드 처리
- add 내의 reduce, reduceat

In [8]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
import functools as ft

In [10]:
ft.reduce(np.add,a)

45

In [12]:
np.add.reduce(a)

45

In [13]:
a.sum()

45

In [14]:
np.add.reduceat(a,[0,4])

array([ 6, 39])

In [16]:
np.add.reduce(a[:4])

6

In [17]:
np.add.reduce(a[4:])

39

### 사용자 유니버셜 함수 정의하기
- 사용자가 직접 정의한 함수를 유니버셜 함수로 등록해서 사용

In [18]:
np.frompyfunc

<function numpy.frompyfunc>

In [20]:
import operator as op

In [21]:
def add(x,y):
    return op.add(x,y)

In [23]:
type(add)

function

In [24]:
a=np.arange(3)
b=np.arange(4,7)
c=add(a,b)
c

array([4, 6, 8])

In [25]:
add_=np.frompyfunc(add,2,1)
type(add_)

numpy.ufunc

In [27]:
d=add_(a,b)
d

array([4, 6, 8], dtype=object)

### vectorize 함수 사용하기

In [28]:
np.vectorize

numpy.vectorize

In [30]:
type(np.vectorize)

type

In [29]:
import operator as op

In [31]:
def mul(x,y):
    return op.mul(x,y)

In [32]:
type(mul)

function

In [33]:
mul_=np.vectorize(mul,otypes=[np.int32])
type(mul_)

numpy.vectorize

In [34]:
a=np.arange(3)
b=np.arange(4,7)
c=mul(a,b)
c

array([ 0,  5, 12])

In [35]:
d=mul_(a,b)
d

array([ 0,  5, 12])

### 함수를 전달 받아서 배열 생성하기

In [37]:
a=np.fromfunction(lambda i,j:i==j,(3,3),dtype=np.int32)
a

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [39]:
b=np.fromfunction(lambda i,j:i+j,(3,3),dtype=np.int32)
b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 파일처리

In [40]:
n=np.random.randn(3,5)
n

array([[-0.18464014,  1.35794892,  0.84699864,  1.27218631,  1.79888453],
       [-0.03589063, -0.73105598, -0.15709949,  0.45434817,  1.74373561],
       [-0.31222356,  0.090805  ,  0.20227855,  0.61738972,  1.69975973]])

In [41]:
n.tofile('n.npy')

In [42]:
m=np.fromfile('n.npy')
m

array([-0.18464014,  1.35794892,  0.84699864,  1.27218631,  1.79888453,
       -0.03589063, -0.73105598, -0.15709949,  0.45434817,  1.74373561,
       -0.31222356,  0.090805  ,  0.20227855,  0.61738972,  1.69975973])

In [43]:
np.save('m.npy',m)
o=np.load('m.npy')
o

array([-0.18464014,  1.35794892,  0.84699864,  1.27218631,  1.79888453,
       -0.03589063, -0.73105598, -0.15709949,  0.45434817,  1.74373561,
       -0.31222356,  0.090805  ,  0.20227855,  0.61738972,  1.69975973])

### 텍스트 파일 처리


In [44]:
a=np.random.randn(3,3)
a

array([[ 2.29728919,  0.0857079 ,  1.07993401],
       [-0.48452924, -1.10858174, -0.70610017],
       [-1.06297801, -0.82495787, -1.11002002]])

In [45]:
np.savetxt('data.txt',a)

In [46]:
# %load data.txt
2.297289194229360287e+00 8.570789881091023243e-02 1.079934012254264664e+00
-4.845292352653787216e-01 -1.108581739947661404e+00 -7.061001726799288614e-01
-1.062978009494642828e+00 -8.249578658292744393e-01 -1.110020021988040284e+00


In [47]:
b=np.loadtxt('data.txt')
b

array([[ 2.29728919,  0.0857079 ,  1.07993401],
       [-0.48452924, -1.10858174, -0.70610017],
       [-1.06297801, -0.82495787, -1.11002002]])

- genfromtxt('file.dat')
- savetxt('file.csv')
- loadtxt('file.csv)

### 직렬화 처리
- npz 확장자

In [48]:
x=np.random.randn(3,5)
x

array([[-0.97239159, -0.53227774,  0.38811853,  0.56502683,  1.7908758 ],
       [-0.91113014,  0.10787821,  0.5893275 , -0.56702786, -1.06594506],
       [ 1.40264604, -1.20159798, -0.38830026, -0.35775057,  1.25579706]])

In [49]:
np.savez('x',x)

In [50]:
y=np.load('x.npz')

In [51]:
y['arr_0']

array([[-0.97239159, -0.53227774,  0.38811853,  0.56502683,  1.7908758 ],
       [-0.91113014,  0.10787821,  0.5893275 , -0.56702786, -1.06594506],
       [ 1.40264604, -1.20159798, -0.38830026, -0.35775057,  1.25579706]])