# Part2. 데이터 핸들링
## 1장 numpy를 활용한 데이터 다루기
### Numpy의 배열객체

In [1]:
# p.65
# Numpy 패키지 불러오기
import numpy as np

# 1-d array 생성
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [2]:
np.array('dataedu')

array('dataedu', dtype='<U7')

In [3]:
# arange([(start,)stop(,step)])
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
# arange는 정수형만 가능한 range 와는 달리 실수도 가능
np.arange(1,6,0.5)  # 1에서 5까지 0.5씩 증가하는 실수열 1차원 배열 생성

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [5]:
range(1,6,0.5)  ## 오류!

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
# ones(shape)
# shape값에 따른 모든 값이 1.(실수)인 배열을 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
# zeros(shape)
# shape값에 따른 모든 값이 0.(실수)인 배열을 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
# full(shape,fill_value)
# shape값에 따른 모든 값이 fill_value인 배열을 생성
np.full(5,4.)

array([4., 4., 4., 4., 4.])

In [9]:
# 배열객체의 데이터 타입(dtype)
# 4가 정수이므로 배열은 정수형이됨
np.full(5,4).dtype

dtype('int32')

In [10]:
# 4.실수형이므로 배열은 실수형이 됨
np.full(5,4.).dtype

dtype('float64')

In [11]:
# 4가 정수이지만, dtype인자를 통해 float로 지정하면 실수형이됨
np.full(5,4,dtype='float').dtype

dtype('float64')

#### 2차원배열

In [12]:
# 2d-array 생성
# 리스트 객체를 2차원 배열로
np.array([[1,3,5,7,9],[2,4,6,8,10]])    # 2행5열

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [13]:
np.array([[1,2,3],[4,5,6],[7,8,9]]) # 3행3열

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# 모든값이 1(정수)이고 행의 수가2, 열의 수가 5개인 2차원 배열 생성
np.ones((2,5),dtype='int')  # dtype생략할 경우 실수로 자동생성

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
# 모든값이 0(정수)이고 행의 수가2, 열의 수가 5개인 2차원 배열 생성
np.zeros((2,5),dtype='int')  # dtype생략할 경우 실수로 자동생성

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [16]:
# 모든값이 5(정수)이고 행의 수가2, 열의 수가 5개인 2차원 배열 생성
np.full((2,5),5,dtype='int')

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [17]:
# 주 대각성분이 1인 행과 열의 수가 5개인 정사각 2차원 배열 생성 (항등행렬과 유사)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# 3d-array 생성
# 리스트 객체를 3차원배열로
np.array([[[1,2,3,4],[5,6,7,8]], # 0층
           [[2,4,6,8],[10,12,14,16]],   # 1층
           [[1,3,5,7],[9,11,13,15]] #2층
           ])   # 3층 2행 4열

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 2,  4,  6,  8],
        [10, 12, 14, 16]],

       [[ 1,  3,  5,  7],
        [ 9, 11, 13, 15]]])

In [19]:
# 모든 값이 1이고 3층 2행 4열인 3차원 배열 생성
np.ones((3,2,4),dtype='int')    # dtype 생략할 경우 실수로 자동 생성

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [20]:
# 모든값이 5이고 3층 2행 4열인 3차원 배열생성
np.full((3,2,4),5)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]]])

### ndarray 정보 확인

In [21]:
# ndarray 생성
# 1d arrray
arr_1d=np.array([1,2,3,4])

# 2d array
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])  # 2행 4열

# 3d array
arr_3d=np.array([
    [[1,2,3,4],[5,6,7,8]],   # 0층
     [[2,4,6,8],[10,12,14,16]], # 1층
     [[1,3,5,7],[9,11,13,15]]    # 2층   
     ])     # 3층 2행 4열

In [22]:
# .shape 
# 배열 객체의 [층,]행,[열]의 수
print(arr_1d.shape) # 1d-array 의 경우 길이정보가 (길이,) 같은 형태로 반환됨
print(arr_2d.shape)

(4,)
(2, 4)


In [23]:
# .size
# 배열객체의 총 원소의 수
print(arr_1d.size)
print(arr_2d.size)
print(arr_3d.size)

4
8
24


In [24]:
# .ndim
# 배열객체의 차원의 수
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


## Numpy의 연산
### ndarray 인덱싱과 슬라이싱

In [25]:
# 인덱싱
# 1d-array 객체 생성
arr_1d=np.array([1,2,3,4,5])
arr_1d[0]   # 가장 처음 (0번)으로부터 값 하나 참조
arr_1d[2]   # 2번 인덱스 위치로부터 값 하나 참조
arr_1d[-1]  # 음수로도 가능

5

In [26]:
# 2d-array 객체 생성
arr_2d=np.array([[1,2,3],[4,5,7],[6,8,9],[11,17,19]])   #4행 3열

# case1
# 처음(0번) 행/열 인덱스로부터 값 하나 참조
print(arr_2d[0,0])

1


In [27]:
# case1(음수로 할 경우)
# -4번 행 인덱스와 -3번 열 인덱스로 부터 값 하나 참조
print(arr_2d[-4,-3])

1


In [28]:
# case2
# 2번 행 인덱스와 1번열 인덱스로 부터 값 하나 참조
print(arr_2d[2,1])

8


### 슬라이싱

In [29]:
# 슬라이싱
# 1d-array객체 생성
arr_1d=np.array([1,2,3,4,5])

In [30]:
# case1
# 처음(0번)부터 2번 인덱스 번호 사이의 구간 추출
print(arr_1d[0:2])

[1 2]


In [31]:
print(arr_1d[:2])   # k1=0으로 생략 가능

[1 2]


In [32]:
# case2
# 1번부터 4번사이의 인덱스 번호 사이의 구간 추출
print(arr_1d[1:4])

[2 3 4]


In [33]:
# -4번부터 -1번사이의 인덱스 번호 사이의 구간 추출
print(arr_1d[-4:-1])

[2 3 4]


In [34]:
# case3
# 3번부터 마지막 5번
print(arr_1d[3:5])

[4 5]


In [35]:
# 3번부터 마지막
print(arr_1d[3:])

[4 5]


In [37]:
# 2d-array 객체 생성
arr_2d=np.array([[1,2,3,5],
                 [1,3,5,7],
                 [2,4,6,9],
                 [7,11,13,17]]) # 4행 4열

In [38]:
# case1
# 행:전체
# 열: 처음부터 1번까지
print(arr_2d[0:4,0])
print(arr_2d[:4,0])
print(arr_2d[:,0])

[1 1 2 7]
[1 1 2 7]
[1 1 2 7]


In [39]:
# case2
# 행/열 : 처음부터 인덱스 3번까지
print(arr_2d[0:3,0:3])
print(arr_2d[:3,:3])
print(arr_2d[:-1,:-1])

[[1 2 3]
 [1 3 5]
 [2 4 6]]
[[1 2 3]
 [1 3 5]
 [2 4 6]]
[[1 2 3]
 [1 3 5]
 [2 4 6]]


### nparray 원소별 연산

In [40]:
# 단일 배열객체에 대한 범용 함수
# 1d-array 객체 생성
arr=np.array([0,1,-4,9,-16,25])
print(arr)

[  0   1  -4   9 -16  25]


In [41]:
# abs : 원소별 절대값을 반환(abs는 파이썬 기본 내장함수로도 가능함)
arr_abs=np.abs(arr)
print(arr_abs)

[ 0  1  4  9 16 25]


In [42]:
# ffabs : 원소의절대값을 반환 (abs보다 빠름)
arr_fabs=np.fabs(arr)
print(arr_fabs)

[ 0.  1.  4.  9. 16. 25.]


In [43]:
# sqrt : 원소별 제곱근 값 반환
# 음수는 nan 반환됨
arr_sqrt=np.sqrt(arr)
print(arr_sqrt)

[ 0.  1. nan  3. nan  5.]


C:\Users\KDP-30\AppData\Local\Temp\ipykernel_2108\1793923975.py:3: RuntimeWarning: invalid value encountered in sqrt
  arr_sqrt=np.sqrt(arr)


In [44]:
# square : 원소별 제곱 값은 반환
arr_square=np.square(arr)
print(arr_square)

[  0   1  16  81 256 625]


In [45]:
# exp : 원소별 밑이 e인 지수 함수 값을 반환
arr_exp=np.exp(arr)
print(arr_exp)

[1.00000000e+00 2.71828183e+00 1.83156389e-02 8.10308393e+03
 1.12535175e-07 7.20048993e+10]


In [46]:
# log: 원소별 자연로그 값을 반환
# 음수는 nan, 0은 -inf반환됨
arr_log=np.log(arr)
print(arr_log)

[      -inf 0.                nan 2.19722458        nan 3.21887582]


C:\Users\KDP-30\AppData\Local\Temp\ipykernel_2108\4158173582.py:3: RuntimeWarning: divide by zero encountered in log
  arr_log=np.log(arr)
C:\Users\KDP-30\AppData\Local\Temp\ipykernel_2108\4158173582.py:3: RuntimeWarning: invalid value encountered in log
  arr_log=np.log(arr)


In [47]:
# log10: 원소별 사용로그 값을 반환
# 음수는 nan,0은  -inf 반환됨
arr_log10=np.log10(arr)
print(arr_log10)

[      -inf 0.                nan 0.95424251        nan 1.39794001]


C:\Users\KDP-30\AppData\Local\Temp\ipykernel_2108\3028066161.py:3: RuntimeWarning: divide by zero encountered in log10
  arr_log10=np.log10(arr)
C:\Users\KDP-30\AppData\Local\Temp\ipykernel_2108\3028066161.py:3: RuntimeWarning: invalid value encountered in log10
  arr_log10=np.log10(arr)


In [48]:
# sign : 원소별 부호 값을 반환
# 양수면 1, 음수면-1, 0은 0을 반환
arr_sign=np.sign(arr)
print(arr_sign)

[ 0  1 -1  1 -1  1]


In [49]:
# 단일 배열객체의 소수점을 처리하는 범용 함수
# 1d-array객체 생성
arr= np.array([1.15,-2.33,3.457,-4.095])
print(arr)

[ 1.15  -2.33   3.457 -4.095]


In [50]:
# round: 원소별 소수점을 원하는 자릿수까지 반올림한 값을 반환
arr_round=np.round(arr) # default는 0
print(arr_round)

[ 1. -2.  3. -4.]


In [51]:
arr_round_decimal_1=np.round(arr,1) # decimals 인자 값만 입력해도 됨
print(arr_round_decimal_1)

[ 1.2 -2.3  3.5 -4.1]


In [52]:
# ceil 원소별 소수점을 올림한 값을 반환
arr_ceil=np.ceil(arr)
print(arr_ceil)

[ 2. -2.  4. -4.]


In [53]:
# floor 원소별 소수점 내림한 값을 반환
arr_floor=np.floor(arr)
print(arr_floor)

[ 1. -3.  3. -5.]


In [55]:
# trunc 원소별 소수점을 잘라버린 값을 반환
arr_trunc=np.trunc(arr)
print(arr_trunc)

[ 1. -2.  3. -4.]


In [57]:
# 서로 배열객체에 대한 범용 함수
# 1d-array 객체 생성
arr_1=np.arange(5)
print(arr_1)

[0 1 2 3 4]


In [59]:
arr_2=np.arange(1,10,step=2)
print(arr_2)

[1 3 5 7 9]


In [60]:
# add 두배열 객체의 원소별 덧셈
arr_add_1=np.add(arr_1,arr_2)
print(arr_add_1)

[ 1  4  7 10 13]


In [61]:
# 연산자 +로 대신가능
arr_add_2=arr_1+arr_2
print(arr_add_2)

[ 1  4  7 10 13]


In [62]:
# substract 두 배열 객체의 원소별 뺼셈
arr_substract_1=np.subtract(arr_1,arr_2)
print(arr_substract_1)

[-1 -2 -3 -4 -5]


In [63]:
# 연산자 -로 대신가능
arr_substract_2=arr_1-arr_2
print(arr_substract_2)

[-1 -2 -3 -4 -5]


In [64]:
# multiply 두 배열객체의 원소별 곱셈
arr_multiply_1=np.multiply(arr_1,arr_2)
print(arr_multiply_1)

[ 0  3 10 21 36]


In [65]:
# 연산자 *로 대체 가능
arr_multiply_2=arr_1*arr_2
print(arr_multiply_2)

[ 0  3 10 21 36]


In [66]:
# divide 두 배열 객체의 원소별 나눗셈
arr_divide_1=np.divide(arr_1,arr_2)
print(arr_divide_1)

[0.         0.33333333 0.4        0.42857143 0.44444444]


In [67]:
# 연산자 /로 대체 가능
arr_divide_2=arr_1/arr_2
print(arr_divide_2)

[0.         0.33333333 0.4        0.42857143 0.44444444]


In [68]:
# mod 두 배열 객체의 원소별 나눈 후 나머지
arr_mod_1=np.mod(arr_1,arr_2)
print(arr_mod_1)

[0 1 2 3 4]


In [70]:
# 연산자 %로 대체가능
arr_mod_2=arr_1%arr_2
print(arr_mod_2)

[0 1 2 3 4]


In [71]:
# 두 배열의 객체가 서로 다른 길이, 차원의 shape를 가질 경우
# case1. 길이가 다른 경우
# 길이가 3인 1d array생성
arr_1d_3=np.array([1,2,3])
print(arr_1d_3) # 확인

[1 2 3]


In [72]:
print(arr_1d_3.shape)

(3,)


In [73]:
# 길이가 1인 1d array 생성
arr_1d_1=np.array([5])
print(arr_1d_1) #확인

[5]


In [74]:
print(arr_1d_1.shape)

(1,)


In [75]:
# 두배열 객체의 합은 길이가 3인 1d array가 됨
arr_add=arr_1d_3+arr_1d_1
print(arr_add)  # 확인

[6 7 8]


In [77]:
# case2 차원이 다른경우
arr_2d_3x3=np.array([[1,4,7],[2,5,8],[3,6,9]])
arr_1d_3=np.array([1,0,-1])

In [78]:
arr_add=arr_2d_3x3+arr_1d_3
print(arr_add)

[[2 4 6]
 [3 5 7]
 [4 6 8]]
