## Numpy의 주요 함수와 메소드
### 형상변환 메소드

In [1]:
import numpy as np
# .reshape()
# 배열객체를 입력된 shape로 변환

# 길이가 8인 1d-array 객체 생성
arr_1d=np.arange(8)
print(arr_1d)

[0 1 2 3 4 5 6 7]


In [ ]:
# 행길이가 2이고 열길이가 4인 2d-array 객체로 변환
arr_2d_2x4=arr_1d.reshape(2,4)
print(arr_2d_2x4)

[[0 1 2 3]
 [4 5 6 7]]


In [3]:
# 행길이가 4이고 열길이가 2인 2d-array 객체로 변환
arr_2d_4x2=arr_1d.reshape(4,2)
print(arr_2d_4x2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [4]:
# reshape 메소드 활용
# 원소가 0~11이면서 층이3이고 행/열의 길이가 3d-array 객체 생성
arr4=np.arange(12).reshape(3,2,2)
print(arr4)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [5]:
arr5=np.arange(12).reshape(3,2,-1)  # 층수3 행수3 남은차원 자동
print(arr5)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [7]:
arr6=np.arange(12).reshape(-1,2,2)  # 행/열의 수는 2로 지정 남은 차원 자동
print(arr6)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [9]:
# 다차원 배열 객체를 1차원 배열로 변환(평탄화)
arr1=np.arange(9)

# reshape메소드를 활용
# (3,3)인 2차원 배열을 길이가 9인 1차원 배열로 변환
arr_1d=arr1.reshape(9)
print(arr_1d)

[0 1 2 3 4 5 6 7 8]


In [11]:
# (3,2,2)인 3차원 배열을 길이가 12인 1차원 배열로 변환
arr4_1d=arr4.reshape(12)
print(arr4_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
# .ravel()
# 다차원 배열객체를 1차원으로 평탄화함
arr2_1d=arr4.ravel()    # 길이를 입력하지 않아도 됨
print(arr2_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [14]:
# .flatten()
# 다차원 배열객체를 1차원으로 평탄화함
arr4_1d=arr4.flatten()  # 길이를 입력하지 않아도됨
print(arr4_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
# .transpose()
# 배열의 축을 교환함
arr_2d=np.arange(8).reshape(4,2)
print(arr_2d)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [16]:
arr_2d_T=arr_2d.transpose() # 축교환
print(arr_2d_T)

[[0 2 4 6]
 [1 3 5 7]]


In [17]:
# .T로 바로 가능
print(arr_2d.T)

[[0 2 4 6]
 [1 3 5 7]]
