## 메소드나 함수로 검색하기
### 메소드로 검색

- item, iview : 검색


In [2]:
import numpy as np

x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
x.item(1)

1

In [5]:
x.item(5)

5

In [6]:
x.item(1,2)

5

In [7]:
x.item((2,2))

8

- itemset : 내부 원소 갱신

In [10]:
x.itemset(2,20)
x

array([[ 0,  1, 20],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [12]:
x.itemset((1,2),20)
x

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [13]:
x.view()

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

- take : 다차원배열 검색

In [14]:
b=np.linspace(1,10,10).reshape(2,5)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [15]:
pos1=[3,4]
b.take(pos1)

array([4., 5.])

In [16]:
pos2=[[0,1],[3,4]]
b.take(pos2)

array([[1., 2.],
       [4., 5.]])

In [17]:
# take를 안썻을경우!
b[[0,1],[3,4]]

array([ 4., 10.])

- put : 내부 원소 변경

In [18]:
c=b.copy()
c.put(pos1,30)
c

array([[ 1.,  2.,  3., 30., 30.],
       [ 6.,  7.,  8.,  9., 10.]])

In [19]:
c.put(pos1,[50,10])
c

array([[ 1.,  2.,  3., 50., 10.],
       [ 6.,  7.,  8.,  9., 10.]])

### 질의함수
- choose : 인덱스로 검색

In [21]:
x= np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
np.choose(0,x)

array([0, 1, 2])

In [23]:
np.choose([0],x)

array([0, 1, 2])

In [24]:
np.choose(tuple([0,1,2]),x)

array([0, 4, 8])

In [25]:
np.choose(tuple([2,1,0]),x)

array([6, 4, 2])

In [31]:
np.choose((2,2,1),x)

array([6, 7, 5])

- where : 조건 판단식을 넣어 검색

In [35]:
np.where(x>4)
# (1,2) (2,0) (2,1) (2,2)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [33]:
x[np.where(x>4)]

array([5, 6, 7, 8])

- select, extract

In [38]:
a= np.select(x>5 , x*2)
a

array([12, 14, 16])

In [39]:
np.extract(x>4 ,x)

array([5, 6, 7, 8])