In [1]:
import numpy as np

# 다차원 배열의 연산
## 산술연산 
### 벡터 덧셈
- 사이즈가 다르면 계산 xx

In [5]:
d=np.array([3,4])
e=np.array([5,6])

In [6]:
d+e

array([ 8, 10])

In [4]:
np.add(d,e)

array([ 8, 10])

### 벡터 뺼셈

In [7]:
d-e

array([-2, -2])

In [8]:
np.subtract(d,e)

array([-2, -2])

In [9]:
d+(-e)

array([-2, -2])

In [10]:
np.add(d,np.negative(e))

array([-2, -2])

### 스칼라곱셈

In [11]:
d=np.array([2,3])

In [12]:
3*d

array([6, 9])

In [14]:
np.multiply(3,d)

array([6, 9])

## 브로드캐스팅 이해하기
### 브로드 캐스팅 : 차원이 다른 배열간의 계산을 할떄는, 계산을 위해 동일한 shape를 구성

In [15]:
x=np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [22]:
# 1차원 배열을 2차원 배열로 변환
z=np.broadcast(x,y)
z

In [19]:
z.shape , z.ndim

((2, 5), 2)

In [20]:
for i in z:
    print(i)

(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 0)
(6, 1)
(7, 2)
(8, 3)
(9, 4)


In [21]:
x+y

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

- 브로드 캐스팅 처리 규칙

In [23]:
x2=np.ones((2,3))
x2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
x1=np.ones(3)
x1

array([1., 1., 1.])

In [32]:
# 마지막 원소 개수 확인
x1.shape,x2.shape

((3,), (2, 3))

In [33]:
x1.shape[0]==x2.shape[1]

True

In [34]:
# 차원 추가
x1=x1[np.newaxis,]
x1.shape

(1, 3)

In [36]:
# 행을 하나 더 추가
x1=np.vstack((x1[0],x1[0]))
x1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
x1.shape==x2.shape

True

In [38]:
x1+x2

array([[2., 2., 2.],
       [2., 2., 2.]])

### 행벡터와 열벡터 브로드캐스팅 확장
- 행벡터와 열벡터의 연산은 동일한 shape를 구성한후 계산

In [40]:
x=np.arange(1,4)
x

array([1, 2, 3])

In [43]:
x1=x.reshape(1,3)
x1

array([[1, 2, 3]])

In [52]:
x2=x[np.newaxis,]
x2

array([[1, 2, 3]])

In [45]:
y=np.arange(1,4)
y

array([1, 2, 3])

In [47]:
y1=y.reshape(3,1)
y1

array([[1],
       [2],
       [3]])

In [50]:
y2=y[:,np.newaxis]
y2

array([[1],
       [2],
       [3]])

In [53]:
np.broadcast_arrays(x1,y1)

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])]

In [54]:
x1+y1

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])