In [3]:
import numpy as np

# 선형대수 기본 알아보기
## 스칼라와 벡터 알아보기

### scalar - 0 차원
- 숫자만 관리
- 차원이 0
- shpae이 없음

In [4]:
a=np.array(43)
type(a)

numpy.ndarray

In [5]:
a

array(43)

In [6]:
a.ndim

0

In [7]:
a.shape

()

### vector - 1차원

In [8]:
v=np.array([43])
type(v)

numpy.ndarray

In [9]:
v

array([43])

In [10]:
v.ndim

1

In [11]:
v.shape

(1,)

### 벡터 생성함수

- arange() : 특정 범위와 간격을 지정해서 배열을 만듬

In [12]:
v=np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
v.dtype

dtype('int32')

In [15]:
v1=np.arange(10.5,20.5,0.5)
v1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [16]:
v1.dtype

dtype('float64')

In [17]:
v1.size

20

In [19]:
la=np.linspace(1,10,10)
la

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
la.dtype

dtype('float64')

- 종료점을 포함하지 않을떄는 endpoint=False 
- retstep=True 로 간격검색

In [23]:
la1=np.linspace(1,10,10,endpoint=False,retstep=True)
la1

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

- logspace() 특정 범위의 log값을 원소로 다차원 배열 만들기

In [24]:
lo=np.logspace(0,2,4)
lo

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [25]:
la2=np.linspace(0,2,4)
la2

array([0.        , 0.66666667, 1.33333333, 2.        ])

### 벡터의 크기
- norm : 벡터의 크기 (lanalg 모듈)

In [26]:
v=np.arange(3,5)
v

array([3, 4])

In [29]:
v_p=np.power(v,2)  # ( 9, 16)
v_r=np.sqrt(np.sum(v_p)) # sqrt(9+16)
v_r

5.0

In [31]:
np.hypot(v[0],v[1])

5.0

In [30]:
np.linalg.norm(v)

5.0

### 표준 단위 벡터(standard unit vectror)
- e1,e2,e3 f로 사용

In [32]:
e1=np.array([1,0,0])
np.linalg.norm(e1)

1.0

In [33]:
e2=np.array([0,1,0])
np.linalg.norm(e2)

1.0

In [35]:
e3=np.array([0,0,1])
np.linalg.norm(e3)

1.0

### 단위벡터
- 벡터의 정규화(nomalize)인 벡터의 크기를 구해 원소에 나눠서 계산

In [36]:
v_3=np.array([1,2,3])
v_3_n=np.linalg.norm(v_3)
v_3_n

3.7416573867739413

In [37]:
v_3_u=v_3/v_3_n
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [38]:
np.linalg.norm(v_3_u)

1.0

### 벡터의 거리
- 피타고라스 정리와 동일

In [39]:
c=np.arange(10,13)
d=np.arange(0,3)
np.sqrt(np.sum(np.square(c-d)))

17.320508075688775

In [40]:
np.linalg.norm(c-d)

17.320508075688775