In [4]:
import numpy as np

# 넘파이 모듈의 함수 특징

- 넘파이 모듈은 동일한 기능을 가진 함수와 메소드를 제공
- 유니버셜 함수 : 반복문을 사용하지 않는 계산 (벡터화 연산)

## 벡터화 연산

In [6]:
a=np.arange(6,10)
a

array([6, 7, 8, 9])

In [7]:
b=np.arange(10,14)
b

array([10, 11, 12, 13])

In [21]:
# 벡터 합으로 계산 (사이즈가 다르면 계산 xx)
c=a+b
c

array([16, 18, 20, 22])

In [9]:
# 벡터 곱으로 계산
c=a*b
c

array([ 60,  77,  96, 117])

## 축 연산
-  sum 으로 전체 합가능
- 2차원은 2개의 축을 가지므로 각 축별로 계산 가능


In [11]:
a2=np.array([1,2,3,4])
a2

array([1, 2, 3, 4])

In [12]:
a2=a2.reshape(2,2)
a2

array([[1, 2],
       [3, 4]])

In [14]:
# 전체 원소 합 구하기
np.sum(a2)

10

In [17]:
# coulumn 방향향 합
np.sum(a2,axis=0)

array([4, 6])

In [19]:
# row 방향 합
np.sum(a2,axis=1)

array([3, 7])

## 배열 할당과 검색

### 배열을 다른 변수에 할당
- 특정 원소를 갱신하면 원본이 갱신

In [22]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [24]:
b=a
b

array([[1, 2],
       [3, 4]])

In [25]:
b[0]=999

In [26]:
a

array([[999, 999],
       [  3,   4]])

In [27]:
b

array([[999, 999],
       [  3,   4]])

### 배열의 복사/뷰 확인
- copy()

In [29]:
f=np.array([4,5,6,7,8])
e=f.copy()
g=f[:]

In [30]:
g.base

array([4, 5, 6, 7, 8])

In [31]:
np.may_share_memory(g,f)

True

### 다차원 배열 검색
- 리스트와 동일한 방식으로 검색

In [36]:
a=np.array([1,2,3,4,5,6,7])
index=1
a.__getitem__(index)
# a[index]랑 동일

2

In [33]:
index=slice(1,3)
a.__getitem__(index)
# a[index]랑 동일

array([2, 3])

In [37]:
index=[1]
a.__getitem__(index)
# a[index]랑 동일

array([2])

In [40]:
index=a<4
print(index)
a.__getitem__(index)
# a[index]랑 동일``

[ True  True  True False False False False]


array([1, 2, 3])

array([1, 2, 3])