In [2]:
import numpy as np

# 다차원 배열의 구조 변경하기
## 변경 및 결합 주요 함수
### 배열의 형상 변경
- reshape : 원소의 갯수를 같게!

In [3]:
x= np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
x1=x.reshape(2,8)
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [5]:
# 원소의 개수가 안맞으면 에러 발생
try:
    x2=x.reshape(4,5)
except Exception as e:
    print(e)

cannot reshape array of size 16 into shape (4,5)


In [7]:
# -1 을 넣으면 자동으로 세팅!
y1=(x.reshape(4,-1))
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 배열의 크기 변경
- resize 
- reshape와는 달리 더 큰 배열로 확장 가능

In [8]:
# 동일 차원에서 크기 확장
a=np.arange(4)
a

array([0, 1, 2, 3])

In [9]:
np.resize(a,8)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [10]:
np.append(a,a)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [11]:
np.resize(a,7)

array([0, 1, 2, 3, 0, 1, 2])

In [12]:
# shape를 다른 차원으로 확대가능
b=np.arange(4)
b.resize((4,4))
b

array([[0, 1, 2, 3],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
# 새로운 배열을 만들떄 refcheck=False 지정
c=np.arange(8)
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
c.resize(4,refcheck=False)
c

array([0, 1, 2, 3])

### 1차원 배열을 2차원 배열로 변경
- meshgrid : 확장된 두개의 다른 배열을 생성

In [18]:
x=np.arange(3)
y=np.arange(4)

In [19]:
x_,y_=np.meshgrid(x,y)

In [20]:
x_

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [21]:
y_

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [23]:
x_1=x.reshape(1,-1)
np.concatenate([x_1,x_1,x_1,x_1])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [24]:
y_1=y.reshape(-1,1)
np.concatenate([y_1,y_1,y_1,y_1],axis=1)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

- mgrid : 인자로 슬라이스 전달하면 두개의 배열을 반환

In [25]:
np.arange(10,30,10)

array([10, 20])

In [26]:
np.arange(1,5)

array([1, 2, 3, 4])

In [27]:
np.broadcast_arrays(np.arange(10,30,10).reshape(2,1),
                    np.arange(1,5).reshape(1,4))

[array([[10, 10, 10, 10],
        [20, 20, 20, 20]]),
 array([[1, 2, 3, 4],
        [1, 2, 3, 4]])]

In [29]:
a,b=np.mgrid[10:30:10,1:5]

In [30]:
a

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [31]:
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

- ogrid : 인자로 슬라이스를 전달하면 2차원 두개의 배열을 반환한다. 
    - 첫번쨰 열은 열백터, 두번쨰는 행벡터

In [33]:
c,d=np.ogrid[10:30:10,1:5]

In [34]:
c

array([[10],
       [20]])

In [35]:
d

array([[1, 2, 3, 4]])

In [36]:
e,f=np.broadcast_arrays(c,d)

In [37]:
e

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [38]:
f

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

### 축이 1인 차원을 줄이기
- squeeze()

In [43]:
x= np.array([[[0],[1],[2]]])

In [44]:
x

array([[[0],
        [1],
        [2]]])

In [45]:
x.shape

(1, 3, 1)

In [46]:
np.squeeze(x)

array([0, 1, 2])

In [47]:
np.squeeze(x,axis=0)

array([[0],
       [1],
       [2]])

In [48]:
np.squeeze(x,axis=2)

array([[0, 1, 2]])

### 내부 원소를 가지고 배열 확대하기
- repeat() : 원소를 반복해서 증가

In [49]:
a=np.linspace(1,5,5,dtype=np.int32)
a

array([1, 2, 3, 4, 5])

In [50]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

- tile() : 주어진 배열의 크기를 확대

In [52]:
e=np.arange(4).reshape(2,2)
e

array([[0, 1],
       [2, 3]])

In [54]:
np.tile(e,2)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

### 배열을 결합하기
- concatenate() : 동일한 형상을 가진 두개의 배열을 만들고 수직과 수평으로 결합

In [55]:
a=np.linspace(1,6,6, dtype=np.int32).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
b=np.linspace(7,13,6, dtype=np.int32).reshape(2,3)
b

array([[ 7,  8,  9],
       [10, 11, 13]])

In [57]:
# 열 크기가 동일할떄 수직결합
np.concatenate([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]])

In [58]:
# 행의 크기가 동일할 때 수평결합
np.concatenate([a,b],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 13]])

### 배열을 쌓기
- stack
- vstack
- hstack

In [59]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [60]:
np.stack([x,y])

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.stack([x,y],axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
a=np.vstack([x,y])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
np.vstack([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [66]:
np.stack([x,y],axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
b=np.hstack([x,y])
b

array([1, 2, 3, 4, 5, 6])

### 배열을 분리하기

In [68]:
a=np.linspace(1,6,6,dtype=np.int32).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
b=np.vstack([a,a])
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [71]:
x,y=np.split(b,[2])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
y

array([[1, 2, 3],
       [4, 5, 6]])

### 배열 쌓기 객체
- 행과 열을 쌓을 떄 r_,c_ 사용

In [74]:
a=np.arange(6).reshape(2,3)
c=np.random.randn(2,3)

In [75]:
np.r_[a,c]

array([[ 0.        ,  1.        ,  2.        ],
       [ 3.        ,  4.        ,  5.        ],
       [ 0.52238097, -0.60951271, -0.89926031],
       [-0.41186066, -0.02719051, -2.91585775]])

In [76]:
np.c_[a,c]

array([[ 0.        ,  1.        ,  2.        ,  0.52238097, -0.60951271,
        -0.89926031],
       [ 3.        ,  4.        ,  5.        , -0.41186066, -0.02719051,
        -2.91585775]])