In [13]:
import numpy as np

## 행렬의 연산
### 벡터의 내적

In [14]:
a=np.array([3,4])
b=np.array([5,6])

In [15]:
a@b

39

In [16]:
np.dot(a,b)

39

In [17]:
np.inner(a,b)

39

### 벡터의 외적

In [18]:
a=np.array([1,4])
b=np.array([3,6])

In [19]:
np.cross(a,b)

array(-6)

In [20]:
c=np.array([1,4,3])
d=np.array([3,4,5])

In [21]:
np.cross(c,d)

array([ 8,  4, -8])

### 행렬 dot product

In [22]:
a=np.array([[3,4],[5,6]])
a

array([[3, 4],
       [5, 6]])

In [23]:
b=np.array([[5,6],[6,7]])
b

array([[5, 6],
       [6, 7]])

In [24]:
np.dot(a,b)

array([[39, 46],
       [61, 72]])

In [25]:
a.dot(b)

array([[39, 46],
       [61, 72]])

In [26]:
a@b

array([[39, 46],
       [61, 72]])

## 행렬식, 역행렬 처리하기
### 행렬식 (determinant)

In [27]:
a=np.array([[3,1],[2,2]])
np.linalg.det(a)

4.000000000000001

### 역행렬(inverse matrix)

In [28]:
a=np.array([[3,2],[6,4]])
np.linalg.det(a)

0.0

In [29]:
b=np.array([[1,2,3],[4,5,6],[3,2,4]])
np.linalg.det(b)

-9.000000000000002

In [31]:
bi=np.linalg.inv(b)
bi

array([[-0.88888889,  0.22222222,  0.33333333],
       [-0.22222222,  0.55555556, -0.66666667],
       [ 0.77777778, -0.44444444,  0.33333333]])

In [33]:
bb=np.dot(b,bi)
bb

array([[ 1.00000000e+00,  1.66533454e-16, -5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00, -2.22044605e-16,  1.00000000e+00]])

In [34]:
np.allclose(np.eye(3),bb)

True