# 다차원 배열의 검색
## 배열의 일반검색
### 색인검색

In [2]:
import numpy as np

In [4]:
v=np.array([1,2,3,4,5])
v[0]

1

In [6]:
v[-1]

5

In [44]:
A=np.array([[1,2,3,4,5],[6,7,8,9,10]])
A[0]

array([1, 2, 3, 4, 5])

In [9]:
A[-1]

array([ 6,  7,  8,  9, 10])

### 슬라이스 검색

In [10]:
B=np.arange(9).reshape(3,3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
B.shape

(3, 3)

In [13]:
B[0,:]

array([0, 1, 2])

In [14]:
B[0]

array([0, 1, 2])

In [15]:
B[:,0]

array([0, 3, 6])

### 생략기호를 사용한 접근
- 생략기호 : ...

In [17]:
A=np.arange(1,60,5).reshape(3,4)
A

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [18]:
A[...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [19]:
A[:2,...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36]])

In [20]:
A[...,:2]

array([[ 1,  6],
       [21, 26],
       [41, 46]])

## 논리식 검색과 팬시검색
### 논리검색

In [21]:
L=np.random.randn(7,4)
L

array([[ 0.36791104,  1.27120663, -1.3777033 , -0.89277508],
       [ 0.67443501,  0.49373474, -2.06195328,  0.58767645],
       [-0.40663476,  0.80898076,  0.40807892,  0.42584073],
       [ 0.99946521,  0.01763127,  0.58273272, -2.40391696],
       [ 0.45267197, -0.80204167,  1.19970433, -0.3326598 ],
       [-0.00580546, -0.2005531 ,  1.29593227,  1.28353423],
       [ 1.11125684, -1.69445081,  0.17337026,  1.22217701]])

In [26]:
# 음수인 원소들만 뽑아줘!
L[L<0]

array([-1.3777033 , -0.89277508, -2.06195328, -0.40663476, -2.40391696,
       -0.80204167, -0.3326598 , -0.00580546, -0.2005531 , -1.69445081])

In [27]:
# 조건식이 참인 원소만 원소 변경해줘!
L[L<0]=999
L

array([[3.67911044e-01, 1.27120663e+00, 9.99000000e+02, 9.99000000e+02],
       [6.74435011e-01, 4.93734744e-01, 9.99000000e+02, 5.87676451e-01],
       [9.99000000e+02, 8.08980764e-01, 4.08078923e-01, 4.25840726e-01],
       [9.99465212e-01, 1.76312651e-02, 5.82732715e-01, 9.99000000e+02],
       [4.52671970e-01, 9.99000000e+02, 1.19970433e+00, 9.99000000e+02],
       [9.99000000e+02, 9.99000000e+02, 1.29593227e+00, 1.28353423e+00],
       [1.11125684e+00, 9.99000000e+02, 1.73370264e-01, 1.22217701e+00]])

In [28]:
# 값이 999인 원소들만 뽑아줘!
LC=L[L==999]
LC

array([999., 999., 999., 999., 999., 999., 999., 999., 999., 999.])

In [30]:
## 논리 검색은 and, or, not 연산 불가
## 대신 logical_and 사용
L=np.arange(0,12)
L

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
try:
    L and L
except Exception as e:
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [32]:
np.logical_and(L,L)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [33]:
L[np.logical_and(L,L)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 팬시검색
- 배열을 전달하여 여러개의 원소를 조회

In [34]:
x=np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
pos2=np.array([1,2,2,2])
x[pos2]

array([2, 3, 3, 3])

- 팬시 검색과 슬라이스 검색의 차이
    - 팬시 검색은 메모리 공유 x
    - 슬라이싱 검색은 메모리공유 o

In [36]:
c=x[pos2]
np.may_share_memory(x,c)

False

In [37]:
y=x[:4]
np.may_share_memory(x,y)

True

- 팬시 검색을...?

In [38]:
x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
x[[3,0]]
# x[3,0] =12

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [41]:
# [1,0]번과 [3,3]번 검색
x[[1,3],[0,3]]

array([ 4, 15])

In [47]:
a=np.array([[2,3,4,5],[8,9,0,1]])
a

array([[2, 3, 4, 5],
       [8, 9, 0, 1]])

In [48]:
type(np.ix_)

numpy._ArrayFunctionDispatcher

In [52]:
a[np.ix_([0,1],[2,3])]
# [0,1]행 [2,3]열을 모두 가져와!

array([[4, 5],
       [0, 1]])

### 팬시 검색 혼용

In [53]:
x=np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
x[0,[0,1]]

array([0, 1])

In [55]:
x[1,[0,1]]

array([5, 6])

In [56]:
x[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
x[[0,1],0]

array([0, 5])

### 팬시검색을 이용한 축소 및 확대

In [61]:
## 축소

x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
a=x[1:,1:]
a

array([[4, 5],
       [7, 8]])

In [62]:
## 확대

a=np.reshape(np.arange(10),(2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

- 차원확대

In [63]:
c=a[[1,1,1],np.newaxis]
c.shape

(3, 1, 5)

In [64]:
c
# 3X1X5

array([[[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]]])

In [67]:
a[[1,1,1]]
# 3X5

array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [72]:
aa=np.array([[5,6,7,8,9]])
aa.shape

(1, 5)

In [74]:
ab=np.array([5,6,7,8,9])
ab.shape

(5,)