In [1]:
import numpy as np

# 선형대수 기본 알아보기

## 행렬 만들기
- 리스트를 array 함수에 전달해서 2차원 배열이 행렬을 만듬
- ndim = 2
- shape = (행,열)

In [2]:
A= np.array([[43],[44]])
type(A)

numpy.ndarray

In [3]:
A

array([[43],
       [44]])

In [4]:
A.dtype

dtype('int32')

In [5]:
A. ndim

2

In [6]:
A.shape

(2, 1)

## 축 알아보기
### 2차원

In [7]:
A=np.array([[2,3],[4,5]])
A.sum()

14

In [8]:
A.sum(axis=0)

array([6, 8])

In [9]:
A.sum(axis=1)

array([5, 9])

## 3차원 텐서(배열)

In [10]:
C=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]]])
C.ndim

3

In [11]:
C.shape

(2, 2, 2)

In [15]:
C[0]

array([[1, 2],
       [3, 4]])

In [14]:
C[1]

array([[5, 6],
       [7, 8]])

In [16]:
C.sum(axis=0)

array([[ 6,  8],
       [10, 12]])

In [17]:
C.sum(axis=1)

array([[ 4,  6],
       [12, 14]])

In [19]:
C.sum(axis=2)

array([[ 3,  7],
       [11, 15]])

## 확장 및 축소하기
### 차원확장

In [20]:
x=np.array([1,2])
x

array([1, 2])

In [21]:
y=np.expand_dims(x,axis=1)
y

array([[1],
       [2]])

In [24]:
z=np.expand_dims(x,axis=0)
z

array([[1, 2]])

### 차원축소

In [25]:
x=np.array([[1,4,5],[4,5,6],[7,8,9]])
x

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# 벡터화시킴 <<많이사용
x.flatten() 

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [27]:
x.ravel()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

## 행렬의 종류
### 정사각행렬
- NxN 행렬

In [34]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a.shape

(3, 3)

In [37]:
# 대각선합
np.trace(a)
a.trace()

15

### 대각행렬

In [38]:
b=np.array([[1,0,0],[0,1,0],[0,0,1]])
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [39]:
b.diagonal()

array([1, 1, 1])

In [40]:
np.diagonal(b)

array([1, 1, 1])

### 삼각행렬

In [41]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [44]:
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])